version: "3"
services:
  db:
    image: mongo
    env_file: .env
  api:
    build: .
    command: "npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ".:/api-restaurants"
    env_file: .env